### PR TITLE
Fix the provider build steps for ignition

### LINKED ISSUE #73: registry.terraform.io/community-terraform-providers/ignition 2.1.1 is not available for linux_ppc64le
Host RHEL 8.3
Repo branch release-4.6
Terraform v0.13.4
+ provider registry.terraform.io/dmacvicar/libvirt v1.0.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

The init fails with 

Error: Failed to install provider

Error while installing community-terraform-providers/ignition v2.1.1: provider
registry.terraform.io/community-terraform-providers/ignition 2.1.1 is not
available for linux_ppc64le

Plus still see the warnings

Warning: Interpolation-only expressions are deprecated

  on modules/5_install/install.tf line 45, in locals:
  45:         release_image_override  = var.enable_local_registry ? "${local.local_registry_ocp_image}" : var.release_image_override

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #73

Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/approve

**Comment by yussufsh** [comment]
@bpradipt Gentle reminder.

**Comment by yussufsh** [comment]
@bpradipt FYA

**Review by bpradipt — APPROVED** [review]
/lgtm

**Pull request merged**
