### PR TITLE
Support TF v0.13 and OCP 4.6

### LINKED ISSUE #43: Support TF v0.13 and OCP 4.6

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #43

Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
I am really sorry for such a big change but had to be done for both TF 13 and OCP 4.6 working with new ignition spec and provider.

**Review by bpradipt — DISMISSED** [review]
/lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @yussufsh

**Pull request merged**
