### PR TITLE
Update helpernode, playbook tag

### PR DESCRIPTION
**Pull request by alishaIBM**
Signed-off-by: Alisha Prabhu <Alisha.Prabhu1@ibm.com>

### CODE REVIEW

**Comment by alishaIBM** [comment]
@Prajyot-Parab could you please review the PR. Thanks !
/cc @pravin-dsilva

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by bpradipt — APPROVED** [review]
/lgtm

**Pull request merged**
